require 'db/migrations/utils'

Sequel.migration do

  up do
    if self[:repository].count == 0
      # If we're running against a brand new installation, bootstrap our basics right away.

      # MAP migration needs this
      alter_table(:physical_representation) do
        add_index([:qsa_id], :name => 'physrep_qsa_id_idx')
      end

      self.transaction do
        self[:group].delete
        self[:permission].delete

        self[:agent_person].multi_insert([
                                           {:id=>1,
                                            :lock_version=>0,
                                            :json_schema_version=>1,
                                            :publish=>1,
                                            :created_by=>nil,
                                            :last_modified_by=>nil,
                                            :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                            :system_mtime=>Time.parse("2020-02-17 23:45:50 UTC"),
                                            :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                            :agent_sha1=>"34b9f8e2743cd3b6350abb05af694ff4ca399402"}])

        self[:name_person].multi_insert([
                                          {:id=>1,
                                           :lock_version=>0,
                                           :json_schema_version=>1,
                                           :agent_person_id=>1,
                                           :primary_name=>"Administrator",
                                           :name_order_id=>947,
                                           :title=>nil,
                                           :prefix=>nil,
                                           :rest_of_name=>nil,
                                           :suffix=>nil,
                                           :fuller_form=>nil,
                                           :number=>nil,
                                           :dates=>nil,
                                           :qualifier=>nil,
                                           :source_id=>236,
                                           :rules_id=>240,
                                           :sort_name=>"Administrator",
                                           :sort_name_auto_generate=>1,
                                           :created_by=>nil,
                                           :last_modified_by=>nil,
                                           :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                           :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                           :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                           :authorized=>1,
                                           :is_display_name=>1}])
        self[:user].multi_insert([
                                   {:id=>1,
                                    :lock_version=>890,
                                    :json_schema_version=>1,
                                    :username=>"admin",
                                    :name=>"Administrator",
                                    :source=>"DBAuth",
                                    :agent_record_id=>1,
                                    :agent_record_type=>"agent_person",
                                    :is_system_user=>1,
                                    :is_hidden_user=>0,
                                    :email=>nil,
                                    :first_name=>nil,
                                    :last_name=>nil,
                                    :telephone=>nil,
                                    :title=>nil,
                                    :department=>nil,
                                    :additional_contact=>nil,
                                    :created_by=>nil,
                                    :last_modified_by=>nil,
                                    :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                    :system_mtime=>Time.parse("2020-02-24 05:12:54 UTC"),
                                    :user_mtime=>Time.parse("2020-02-24 05:12:54 UTC")}])

        self[:auth_db].multi_insert([
                                      {:id=>1,
                                       :username=>"admin",
                                       :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                       :system_mtime=>Time.parse("2019-04-01 05:18:14 UTC"),
                                       :pwhash=>"$2a$10$Yi9D/WF46zYFLZhU/gS3OerxNR4p.4g8HNdc4b84LZS7ZzCP9R1sy"}])


        self[:agent_corporate_entity].multi_insert([
                                                     {:id=>1,
                                                      :lock_version=>0,
                                                      :json_schema_version=>1,
                                                      :publish=>1,
                                                      :created_by=>"admin",
                                                      :last_modified_by=>"admin",
                                                      :create_time=>Time.parse("2019-04-01 05:20:53 UTC"),
                                                      :system_mtime=>Time.parse("2020-02-21 00:15:04 UTC"),
                                                      :user_mtime=>Time.parse("2019-10-13 07:07:37 UTC"),
                                                      :agent_sha1=>"2558f4f71262d7bed9bafb41d15e113dc747d741",
                                                      :agency_category_id=>nil,
                                                      :registration_state=>"approved",
                                                      :registration_last_action=>nil,
                                                      :registration_last_user=>nil,
                                                      :registration_last_time=>nil,
                                                      :qsa_id=>1,
                                                      :agency_note=>nil,
                                                      :original_registration_date=>nil}])
        self[:name_corporate_entity].multi_insert([
                                                    {:id=>1,
                                                     :lock_version=>0,
                                                     :json_schema_version=>1,
                                                     :agent_corporate_entity_id=>1,
                                                     :primary_name=>"Queensland State Archives Repository",
                                                     :subordinate_name_1=>nil,
                                                     :subordinate_name_2=>nil,
                                                     :number=>nil,
                                                     :dates=>nil,
                                                     :qualifier=>nil,
                                                     :source_id=>236,
                                                     :rules_id=>nil,
                                                     :sort_name=>"Queensland State Archives Repository",
                                                     :sort_name_auto_generate=>1,
                                                     :created_by=>"admin",
                                                     :last_modified_by=>"admin",
                                                     :create_time=>Time.parse("2019-10-13 07:07:37 UTC"),
                                                     :system_mtime=>Time.parse("2019-10-13 07:07:37 UTC"),
                                                     :user_mtime=>Time.parse("2019-10-13 07:07:37 UTC"),
                                                     :authorized=>1,
                                                     :is_display_name=>1}])

        self[:date].multi_insert([
                                  {:id=>1,
                                   :lock_version=>0,
                                   :json_schema_version=>1,
                                   :agent_corporate_entity_id=>1,
                                   :begin=>'1959',
                                   :date_type_id=>1281,
                                   :label_id=>916,
                                   :created_by=>"admin",
                                   :last_modified_by=>"admin",
                                   :create_time=>Time.parse("2019-10-13 07:07:37 UTC"),
                                   :system_mtime=>Time.parse("2019-10-13 07:07:37 UTC"),
                                   :user_mtime=>Time.parse("2019-10-13 07:07:37 UTC")}])

        self[:repository].multi_insert([
                                         {:id=>1,
                                          :lock_version=>0,
                                          :json_schema_version=>1,
                                          :repo_code=>"_archivesspace",
                                          :name=>"Global repository",
                                          :org_code=>nil,
                                          :parent_institution_name=>nil,
                                          :url=>nil,
                                          :image_url=>nil,
                                          :contact_persons=>nil,
                                          :country_id=>nil,
                                          :agent_representation_id=>nil,
                                          :hidden=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:20 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:20 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:20 UTC"),
                                          :publish=>0,
                                          :description=>nil,
                                          :oai_is_disabled=>0,
                                          :oai_sets_available=>nil},
                                         {:id=>2,
                                          :lock_version=>0,
                                          :json_schema_version=>1,
                                          :repo_code=>"QSA Test",
                                          :name=>"Queensland State Archives Repository",
                                          :org_code=>nil,
                                          :parent_institution_name=>nil,
                                          :url=>nil,
                                          :image_url=>nil,
                                          :contact_persons=>nil,
                                          :country_id=>nil,
                                          :agent_representation_id=>1,
                                          :hidden=>0,
                                          :created_by=>"admin",
                                          :last_modified_by=>"admin",
                                          :create_time=>Time.parse("2019-04-01 05:20:53 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:20:53 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:20:53 UTC"),
                                          :publish=>1,
                                          :description=>nil,
                                          :oai_is_disabled=>0,
                                          :oai_sets_available=>nil}])

        self[:permission].multi_insert([
                                         {:id=>1,
                                          :permission_code=>"create_job",
                                          :description=>"The ability to create background jobs",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>"admin",
                                          :last_modified_by=>"admin",
                                          :create_time=>Time.parse("2019-04-01 05:15:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:15:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:15:21 UTC")},
                                         {:id=>2,
                                          :permission_code=>"cancel_job",
                                          :description=>"The ability to cancel background jobs",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>"admin",
                                          :last_modified_by=>"admin",
                                          :create_time=>Time.parse("2019-04-01 05:15:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:15:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:15:21 UTC")},
                                         {:id=>3,
                                          :permission_code=>"manage_enumeration_record",
                                          :description=>
                                          "The ability to create, modify and delete a controlled vocabulary list record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>"admin",
                                          :last_modified_by=>"admin",
                                          :create_time=>Time.parse("2019-04-01 05:15:27 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:15:27 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:15:27 UTC")},
                                         {:id=>4,
                                          :permission_code=>"manage_agency_registration",
                                          :description=>"The ability to manage the agency registration workflow",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:15:50 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:15:50 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:15:50 UTC")},
                                         {:id=>5,
                                          :permission_code=>"mog_update",
                                          :description=>"The ability to run Machinery of Government updates",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>"admin",
                                          :last_modified_by=>"admin",
                                          :create_time=>Time.parse("2019-04-01 05:15:55 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:15:55 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:15:55 UTC")},
                                         {:id=>6,
                                          :permission_code=>"administer_system",
                                          :description=>"The ability to act as a system administrator",
                                          :level=>"global",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>7,
                                          :permission_code=>"manage_users",
                                          :description=>"The ability to manage user accounts while logged in",
                                          :level=>"global",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>8,
                                          :permission_code=>"become_user",
                                          :description=>"The ability to masquerade as another user",
                                          :level=>"global",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>9,
                                          :permission_code=>"view_all_records",
                                          :description=>"The ability to view any record in the system",
                                          :level=>"global",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>10,
                                          :permission_code=>"create_repository",
                                          :description=>"The ability to create new repositories",
                                          :level=>"global",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>11,
                                          :permission_code=>"delete_repository",
                                          :description=>"The ability to delete a repository",
                                          :level=>"global",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>12,
                                          :permission_code=>"transfer_repository",
                                          :description=>"The ability to transfer the contents of a repository",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>13,
                                          :permission_code=>"index_system",
                                          :description=>"The ability to read any record for indexing",
                                          :level=>"global",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                         {:id=>14,
                                          :permission_code=>"manage_repository",
                                          :description=>"The ability to manage a given repository",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>15,
                                          :permission_code=>"update_accession_record",
                                          :description=>"The ability to create and modify accessions records",
                                          :level=>"repository",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>16,
                                          :permission_code=>"update_resource_record",
                                          :description=>
                                          "The ability to create and modify series, item and representation records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:55 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>17,
                                          :permission_code=>"update_digital_object_record",
                                          :description=>"The ability to create and modify digital objects records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>18,
                                          :permission_code=>"update_event_record",
                                          :description=>"The ability to create and modify event records",
                                          :level=>"repository",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>19,
                                          :permission_code=>"delete_event_record",
                                          :description=>"The ability to delete event records",
                                          :level=>"repository",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>20,
                                          :permission_code=>"suppress_archival_record",
                                          :description=>
                                          "The ability to suppress the major archival record types: accessions/resources/digital objects/components/collection management/events",
                                          :level=>"repository",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>21,
                                          :permission_code=>"transfer_archival_record",
                                          :description=>
                                          "The ability to transfer records between different repositories",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>22,
                                          :permission_code=>"delete_archival_record",
                                          :description=>
                                          "The ability to delete the major archival record types: accessions/resources/digital objects/components/collection management/events",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>23,
                                          :permission_code=>"view_suppressed",
                                          :description=>"The ability to view suppressed records in a given repository",
                                          :level=>"repository",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>24,
                                          :permission_code=>"view_repository",
                                          :description=>"The ability to view a given repository",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>25,
                                          :permission_code=>"update_classification_record",
                                          :description=>"The ability to create and modify classification records",
                                          :level=>"repository",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>26,
                                          :permission_code=>"delete_classification_record",
                                          :description=>"The ability to delete classification records",
                                          :level=>"repository",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>27,
                                          :permission_code=>"mediate_edits",
                                          :description=>"Track concurrent updates to records",
                                          :level=>"global",
                                          :system=>1,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>28,
                                          :permission_code=>"import_records",
                                          :description=>"The ability to initiate an importer job",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>29,
                                          :permission_code=>"cancel_importer_job",
                                          :description=>"The ability to cancel a queued or running importer job",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>30,
                                          :permission_code=>"manage_subject_record",
                                          :description=>"The ability to create, modify and delete a subject record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>31,
                                          :permission_code=>"manage_agent_record",
                                          :description=>"The ability to create, modify and delete an agent record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>32,
                                          :permission_code=>"manage_vocabulary_record",
                                          :description=>"The ability to create, modify and delete a vocabulary record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>33,
                                          :permission_code=>"merge_agents_and_subjects",
                                          :description=>"The ability to merge agent/subject records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>34,
                                          :permission_code=>"merge_archival_record",
                                          :description=>"The ability to merge archival records records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>35,
                                          :permission_code=>"manage_rde_templates",
                                          :description=>"The ability to create and delete RDE templates",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>36,
                                          :permission_code=>"update_container_record",
                                          :description=>"The ability to create and update container records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>37,
                                          :permission_code=>"manage_container_record",
                                          :description=>"The ability to delete and bulk update container records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>38,
                                          :permission_code=>"manage_container_profile_record",
                                          :description=>
                                          "The ability to create, modify and delete a container profile record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>39,
                                          :permission_code=>"manage_location_profile_record",
                                          :description=>
                                          "The ability to create, modify and delete a location profile record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>40,
                                          :permission_code=>"update_assessment_record",
                                          :description=>"The ability to create and modify assessment records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>41,
                                          :permission_code=>"delete_assessment_record",
                                          :description=>"The ability to delete assessment records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>42,
                                          :permission_code=>"manage_assessment_attributes",
                                          :description=>"The ability to managae assessment attribute definitions",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:22 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:22 UTC")},
                                         {:id=>43,
                                          :permission_code=>"manage_function_record",
                                          :description=>"The ability to create, modify and delete a function record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:24 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:24 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:24 UTC")},
                                         {:id=>44,
                                          :permission_code=>"manage_mandate_record",
                                          :description=>"The ability to create, modify and delete a function record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2019-04-01 05:16:24 UTC"),
                                          :system_mtime=>Time.parse("2019-04-01 05:16:24 UTC"),
                                          :user_mtime=>Time.parse("2019-04-01 05:16:24 UTC")},
                                         {:id=>45,
                                          :permission_code=>"manage_publication",
                                          :description=>
                                          "The ability to publish and unpublish records to the public website",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>46,
                                          :permission_code=>"manage_reading_room_requests",
                                          :description=>"The ability to process reading room requests",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>47,
                                          :permission_code=>"set_raps",
                                          :description=>"The ability to set Restricted Access Periods on records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>48,
                                          :permission_code=>"manage_conservation_assessment",
                                          :description=>
                                          "The ability to create, modify and delete conversion requests and assessments",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>49,
                                          :permission_code=>"manage_fee_schedules",
                                          :description=>"The ability to create, modify and delete fee schedules",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>50,
                                          :permission_code=>"manage_transfers",
                                          :description=>"The ability to manage transfers",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>51,
                                          :permission_code=>"manage_file_issues",
                                          :description=>"The ability to manage file issues",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>53,
                                          :permission_code=>"manage_agency_deletion",
                                          :description=>"The ability to manage the deletion of agency records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>54,
                                          :permission_code=>"approve_records",
                                          :description=>"The ability to archivist approve a record",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:52 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:52 UTC")},
                                         {:id=>55,
                                          :permission_code=>"manage_closed_record_approval",
                                          :description=>"The ability to manage agency approval of closed records",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-01-20 00:29:56 UTC"),
                                          :system_mtime=>Time.parse("2020-01-20 00:29:56 UTC"),
                                          :user_mtime=>Time.parse("2020-01-20 00:29:56 UTC")},
                                         {:id=>56,
                                          :permission_code=>"manage_search_requests",
                                          :description=>"The ability to manage search requests",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-02-03 00:06:53 UTC"),
                                          :system_mtime=>Time.parse("2020-02-03 00:06:53 UTC"),
                                          :user_mtime=>Time.parse("2020-02-03 00:06:53 UTC")},
                                         {:id=>57,
                                          :permission_code=>"create_batch",
                                          :description=>"The ability to create batches",
                                          :level=>"repository",
                                          :system=>0,
                                          :created_by=>nil,
                                          :last_modified_by=>nil,
                                          :create_time=>Time.parse("2020-02-03 00:06:53 UTC"),
                                          :system_mtime=>Time.parse("2020-02-03 00:06:53 UTC"),
                                          :user_mtime=>Time.parse("2020-02-03 00:06:53 UTC")}])
        self[:group].multi_insert([
                                    {:id=>1,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>1,
                                     :group_code=>"administrators",
                                     :group_code_norm=>"administrators",
                                     :description=>"Administrators",
                                     :created_by=>nil,
                                     :last_modified_by=>nil,
                                     :create_time=>Time.parse("2019-04-01 05:16:21 UTC"),
                                     :system_mtime=>Time.parse("2019-04-01 05:16:21 UTC"),
                                     :user_mtime=>Time.parse("2019-04-01 05:16:21 UTC")},
                                    {:id=>6,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-archivists-other",
                                     :group_code_norm=>"repository-archivists-other",
                                     :description=>"Archivists - Other of the QSA repository",
                                     :created_by=>"admin",
                                     :last_modified_by=>"admin",
                                     :create_time=>Time.parse("2019-04-01 05:20:53 UTC"),
                                     :system_mtime=>Time.parse("2020-02-19 00:44:30 UTC"),
                                     :user_mtime=>Time.parse("2020-02-19 00:44:30 UTC")},
                                    {:id=>17,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-collection-archivists",
                                     :group_code_norm=>"repository-collection-archivists",
                                     :description=>"Collection Archivists of the QSA repository",
                                     :created_by=>nil,
                                     :last_modified_by=>"test_user3",
                                     :create_time=>Time.parse("2020-01-20 00:29:51 UTC"),
                                     :system_mtime=>Time.parse("2020-01-22 03:54:06 UTC"),
                                     :user_mtime=>Time.parse("2020-01-22 03:54:06 UTC")},
                                    {:id=>7,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-collection-managers",
                                     :group_code_norm=>"repository-collection-managers",
                                     :description=>
                                     "Managers of Collection Enrichment and Discovery of the QSA repository",
                                     :created_by=>"admin",
                                     :last_modified_by=>"test_user2",
                                     :create_time=>Time.parse("2019-04-01 05:20:53 UTC"),
                                     :system_mtime=>Time.parse("2020-01-22 02:53:24 UTC"),
                                     :user_mtime=>Time.parse("2020-01-22 02:53:24 UTC")},
                                    {:id=>9,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-data-entry-volunteers",
                                     :group_code_norm=>"repository-data-entry-volunteers",
                                     :description=>"Data Entry/ Volunteers of the QSA repository",
                                     :created_by=>"admin",
                                     :last_modified_by=>"test_user5",
                                     :create_time=>Time.parse("2019-04-01 05:20:54 UTC"),
                                     :system_mtime=>Time.parse("2020-01-22 02:06:51 UTC"),
                                     :user_mtime=>Time.parse("2020-01-22 02:06:51 UTC")},
                                    {:id=>19,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-preservation-team",
                                     :group_code_norm=>"repository-preservation-team",
                                     :description=>"Preservation Team of the QSA repository",
                                     :created_by=>nil,
                                     :last_modified_by=>"admin",
                                     :create_time=>Time.parse("2020-01-20 00:29:51 UTC"),
                                     :system_mtime=>Time.parse("2020-01-20 03:46:01 UTC"),
                                     :user_mtime=>Time.parse("2020-01-20 03:46:01 UTC")},
                                    {:id=>18,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-reading-room-staff",
                                     :group_code_norm=>"repository-reading-room-staff",
                                     :description=>"Reading room staff of the QSA repository",
                                     :created_by=>nil,
                                     :last_modified_by=>nil,
                                     :create_time=>Time.parse("2020-01-20 00:29:51 UTC"),
                                     :system_mtime=>Time.parse("2020-01-20 00:29:51 UTC"),
                                     :user_mtime=>Time.parse("2020-01-20 00:29:51 UTC")},
                                    {:id=>5,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-senior-archivists",
                                     :group_code_norm=>"repository-senior-archivists",
                                     :description=>"Senior Archivists of the QSA repository",
                                     :created_by=>"admin",
                                     :last_modified_by=>"glen",
                                     :create_time=>Time.parse("2019-04-01 05:20:53 UTC"),
                                     :system_mtime=>Time.parse("2020-01-22 05:13:15 UTC"),
                                     :user_mtime=>Time.parse("2020-01-22 05:13:15 UTC")},
                                    {:id=>8,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-transfer-file-issue",
                                     :group_code_norm=>"repository-transfer-file-issue",
                                     :description=>"Repository/ transfer/file issue of the QSA repository",
                                     :created_by=>"admin",
                                     :last_modified_by=>"test_user1",
                                     :create_time=>Time.parse("2019-04-01 05:20:54 UTC"),
                                     :system_mtime=>Time.parse("2020-01-22 05:33:35 UTC"),
                                     :user_mtime=>Time.parse("2020-01-22 05:33:35 UTC")},
                                    {:id=>10,
                                     :lock_version=>0,
                                     :json_schema_version=>1,
                                     :repo_id=>2,
                                     :group_code=>"repository-viewers",
                                     :group_code_norm=>"repository-viewers",
                                     :description=>"Viewers of the QSA repository",
                                     :created_by=>"admin",
                                     :last_modified_by=>"glen",
                                     :create_time=>Time.parse("2019-04-01 05:20:54 UTC"),
                                     :system_mtime=>Time.parse("2020-01-22 05:12:51 UTC"),
                                     :user_mtime=>Time.parse("2020-01-22 05:12:51 UTC")}])
        self[:group_permission].multi_insert([
                                               {:permission_id=>6, :group_id=>1},
                                               {:permission_id=>7, :group_id=>1},
                                               {:permission_id=>8, :group_id=>1},
                                               {:permission_id=>9, :group_id=>1},
                                               {:permission_id=>10, :group_id=>1},
                                               {:permission_id=>11, :group_id=>1},
                                               {:permission_id=>12, :group_id=>1},
                                               {:permission_id=>13, :group_id=>1},
                                               {:permission_id=>14, :group_id=>1},
                                               {:permission_id=>15, :group_id=>1},
                                               {:permission_id=>16, :group_id=>1},
                                               {:permission_id=>17, :group_id=>1},
                                               {:permission_id=>18, :group_id=>1},
                                               {:permission_id=>19, :group_id=>1},
                                               {:permission_id=>20, :group_id=>1},
                                               {:permission_id=>21, :group_id=>1},
                                               {:permission_id=>22, :group_id=>1},
                                               {:permission_id=>23, :group_id=>1},
                                               {:permission_id=>24, :group_id=>1},
                                               {:permission_id=>25, :group_id=>1},
                                               {:permission_id=>26, :group_id=>1},
                                               {:permission_id=>27, :group_id=>1},
                                               {:permission_id=>28, :group_id=>1},
                                               {:permission_id=>29, :group_id=>1},
                                               {:permission_id=>1, :group_id=>1},
                                               {:permission_id=>2, :group_id=>1},
                                               {:permission_id=>30, :group_id=>1},
                                               {:permission_id=>31, :group_id=>1},
                                               {:permission_id=>32, :group_id=>1},
                                               {:permission_id=>3, :group_id=>1},
                                               {:permission_id=>33, :group_id=>1},
                                               {:permission_id=>34, :group_id=>1},
                                               {:permission_id=>35, :group_id=>1},
                                               {:permission_id=>36, :group_id=>1},
                                               {:permission_id=>37, :group_id=>1},
                                               {:permission_id=>38, :group_id=>1},
                                               {:permission_id=>39, :group_id=>1},
                                               {:permission_id=>40, :group_id=>1},
                                               {:permission_id=>41, :group_id=>1},
                                               {:permission_id=>42, :group_id=>1},
                                               {:permission_id=>43, :group_id=>1},
                                               {:permission_id=>44, :group_id=>1},
                                               {:permission_id=>4, :group_id=>1},
                                               {:permission_id=>5, :group_id=>1},
                                               {:permission_id=>45, :group_id=>1},
                                               {:permission_id=>46, :group_id=>1},
                                               {:permission_id=>47, :group_id=>1},
                                               {:permission_id=>48, :group_id=>1},
                                               {:permission_id=>49, :group_id=>1},
                                               {:permission_id=>50, :group_id=>1},
                                               {:permission_id=>51, :group_id=>1},
                                               {:permission_id=>53, :group_id=>1},
                                               {:permission_id=>54, :group_id=>1},
                                               {:permission_id=>55, :group_id=>1},
                                               {:permission_id=>56, :group_id=>1},
                                               {:permission_id=>57, :group_id=>1},
                                               {:permission_id=>1, :group_id=>6},
                                               {:permission_id=>2, :group_id=>6},
                                               {:permission_id=>16, :group_id=>6},
                                               {:permission_id=>17, :group_id=>6},
                                               {:permission_id=>21, :group_id=>6},
                                               {:permission_id=>24, :group_id=>6},
                                               {:permission_id=>30, :group_id=>6},
                                               {:permission_id=>34, :group_id=>6},
                                               {:permission_id=>46, :group_id=>6},
                                               {:permission_id=>47, :group_id=>6},
                                               {:permission_id=>53, :group_id=>6},
                                               {:permission_id=>54, :group_id=>6},
                                               {:permission_id=>55, :group_id=>6},
                                               {:permission_id=>57, :group_id=>6},
                                               {:permission_id=>1, :group_id=>17},
                                               {:permission_id=>2, :group_id=>17},
                                               {:permission_id=>16, :group_id=>17},
                                               {:permission_id=>17, :group_id=>17},
                                               {:permission_id=>21, :group_id=>17},
                                               {:permission_id=>24, :group_id=>17},
                                               {:permission_id=>28, :group_id=>17},
                                               {:permission_id=>29, :group_id=>17},
                                               {:permission_id=>30, :group_id=>17},
                                               {:permission_id=>31, :group_id=>17},
                                               {:permission_id=>34, :group_id=>17},
                                               {:permission_id=>35, :group_id=>17},
                                               {:permission_id=>36, :group_id=>17},
                                               {:permission_id=>37, :group_id=>17},
                                               {:permission_id=>38, :group_id=>17},
                                               {:permission_id=>39, :group_id=>17},
                                               {:permission_id=>46, :group_id=>17},
                                               {:permission_id=>47, :group_id=>17},
                                               {:permission_id=>54, :group_id=>17},
                                               {:permission_id=>55, :group_id=>17},
                                               {:permission_id=>57, :group_id=>17},
                                               {:permission_id=>1, :group_id=>7},
                                               {:permission_id=>2, :group_id=>7},
                                               {:permission_id=>4, :group_id=>7},
                                               {:permission_id=>5, :group_id=>7},
                                               {:permission_id=>12, :group_id=>7},
                                               {:permission_id=>14, :group_id=>7},
                                               {:permission_id=>16, :group_id=>7},
                                               {:permission_id=>17, :group_id=>7},
                                               {:permission_id=>21, :group_id=>7},
                                               {:permission_id=>22, :group_id=>7},
                                               {:permission_id=>24, :group_id=>7},
                                               {:permission_id=>28, :group_id=>7},
                                               {:permission_id=>29, :group_id=>7},
                                               {:permission_id=>30, :group_id=>7},
                                               {:permission_id=>31, :group_id=>7},
                                               {:permission_id=>32, :group_id=>7},
                                               {:permission_id=>33, :group_id=>7},
                                               {:permission_id=>34, :group_id=>7},
                                               {:permission_id=>35, :group_id=>7},
                                               {:permission_id=>36, :group_id=>7},
                                               {:permission_id=>37, :group_id=>7},
                                               {:permission_id=>38, :group_id=>7},
                                               {:permission_id=>39, :group_id=>7},
                                               {:permission_id=>40, :group_id=>7},
                                               {:permission_id=>41, :group_id=>7},
                                               {:permission_id=>42, :group_id=>7},
                                               {:permission_id=>43, :group_id=>7},
                                               {:permission_id=>44, :group_id=>7},
                                               {:permission_id=>45, :group_id=>7},
                                               {:permission_id=>46, :group_id=>7},
                                               {:permission_id=>47, :group_id=>7},
                                               {:permission_id=>48, :group_id=>7},
                                               {:permission_id=>49, :group_id=>7},
                                               {:permission_id=>50, :group_id=>7},
                                               {:permission_id=>51, :group_id=>7},
                                               {:permission_id=>53, :group_id=>7},
                                               {:permission_id=>54, :group_id=>7},
                                               {:permission_id=>55, :group_id=>7},
                                               {:permission_id=>56, :group_id=>7},
                                               {:permission_id=>57, :group_id=>7},
                                               {:permission_id=>24, :group_id=>9},
                                               {:permission_id=>1, :group_id=>19},
                                               {:permission_id=>2, :group_id=>19},
                                               {:permission_id=>16, :group_id=>19},
                                               {:permission_id=>17, :group_id=>19},
                                               {:permission_id=>21, :group_id=>19},
                                               {:permission_id=>24, :group_id=>19},
                                               {:permission_id=>30, :group_id=>19},
                                               {:permission_id=>34, :group_id=>19},
                                               {:permission_id=>36, :group_id=>19},
                                               {:permission_id=>37, :group_id=>19},
                                               {:permission_id=>38, :group_id=>19},
                                               {:permission_id=>39, :group_id=>19},
                                               {:permission_id=>40, :group_id=>19},
                                               {:permission_id=>41, :group_id=>19},
                                               {:permission_id=>42, :group_id=>19},
                                               {:permission_id=>46, :group_id=>19},
                                               {:permission_id=>48, :group_id=>19},
                                               {:permission_id=>57, :group_id=>19},
                                               {:permission_id=>24, :group_id=>18},
                                               {:permission_id=>46, :group_id=>18},
                                               {:permission_id=>55, :group_id=>18},
                                               {:permission_id=>1, :group_id=>5},
                                               {:permission_id=>2, :group_id=>5},
                                               {:permission_id=>4, :group_id=>5},
                                               {:permission_id=>5, :group_id=>5},
                                               {:permission_id=>12, :group_id=>5},
                                               {:permission_id=>14, :group_id=>5},
                                               {:permission_id=>16, :group_id=>5},
                                               {:permission_id=>17, :group_id=>5},
                                               {:permission_id=>21, :group_id=>5},
                                               {:permission_id=>22, :group_id=>5},
                                               {:permission_id=>24, :group_id=>5},
                                               {:permission_id=>28, :group_id=>5},
                                               {:permission_id=>29, :group_id=>5},
                                               {:permission_id=>30, :group_id=>5},
                                               {:permission_id=>31, :group_id=>5},
                                               {:permission_id=>32, :group_id=>5},
                                               {:permission_id=>33, :group_id=>5},
                                               {:permission_id=>34, :group_id=>5},
                                               {:permission_id=>35, :group_id=>5},
                                               {:permission_id=>36, :group_id=>5},
                                               {:permission_id=>37, :group_id=>5},
                                               {:permission_id=>38, :group_id=>5},
                                               {:permission_id=>39, :group_id=>5},
                                               {:permission_id=>40, :group_id=>5},
                                               {:permission_id=>41, :group_id=>5},
                                               {:permission_id=>42, :group_id=>5},
                                               {:permission_id=>43, :group_id=>5},
                                               {:permission_id=>44, :group_id=>5},
                                               {:permission_id=>45, :group_id=>5},
                                               {:permission_id=>46, :group_id=>5},
                                               {:permission_id=>47, :group_id=>5},
                                               {:permission_id=>48, :group_id=>5},
                                               {:permission_id=>49, :group_id=>5},
                                               {:permission_id=>50, :group_id=>5},
                                               {:permission_id=>51, :group_id=>5},
                                               {:permission_id=>53, :group_id=>5},
                                               {:permission_id=>54, :group_id=>5},
                                               {:permission_id=>55, :group_id=>5},
                                               {:permission_id=>56, :group_id=>5},
                                               {:permission_id=>57, :group_id=>5},
                                               {:permission_id=>1, :group_id=>8},
                                               {:permission_id=>2, :group_id=>8},
                                               {:permission_id=>16, :group_id=>8},
                                               {:permission_id=>17, :group_id=>8},
                                               {:permission_id=>24, :group_id=>8},
                                               {:permission_id=>28, :group_id=>8},
                                               {:permission_id=>29, :group_id=>8},
                                               {:permission_id=>30, :group_id=>8},
                                               {:permission_id=>34, :group_id=>8},
                                               {:permission_id=>36, :group_id=>8},
                                               {:permission_id=>37, :group_id=>8},
                                               {:permission_id=>38, :group_id=>8},
                                               {:permission_id=>39, :group_id=>8},
                                               {:permission_id=>46, :group_id=>8},
                                               {:permission_id=>47, :group_id=>8},
                                               {:permission_id=>50, :group_id=>8},
                                               {:permission_id=>51, :group_id=>8},
                                               {:permission_id=>56, :group_id=>8},
                                               {:permission_id=>57, :group_id=>8},
                                               {:permission_id=>24, :group_id=>10}])

        # Add the admin to the administrators group
        self[:group_user].multi_insert([{:user_id => 1, :group_id => 1}])
      end
    end
  end
end
