QSAId.register(:resource, :existing_id_field => :id_0, :prefix => 'S')
QSAId.register(:archival_object, :existing_id_field => :ref_id, :prefix => 'R')
QSAId.register(:digital_object, :existing_id_field => :digital_object_id, :prefix => 'D')
QSAId.register(:function, :prefix => 'F')
QSAId.register(:mandate, :prefix => 'M')
QSAId.register(:agent_corporate_entity, :prefix => 'A')
QSAId.register(:physical_representation, :prefix => 'PR')
QSAId.register(:digital_representation, :prefix => 'DR')
QSAId.register(:assessment, :prefix => 'AS', :use_database_id => true)
QSAId.register(:conservation_request, :prefix => 'CR', :use_database_id => true)
QSAId.register(:batch, :prefix => 'BA', :use_database_id => true)
QSAId.register(:top_container, :prefix => 'TC', :use_database_id => true)
