QSAId.register(:resource, :id_0)
QSAId.register(:archival_object, :ref_id)
QSAId.register(:digital_object, :digital_object_id)
QSAId.register(:function)
QSAId.register(:mandate)
QSAId.register(:accession, :id_0)
QSAId.register(:agent_corporate_entity)
QSAId.register(:physical_representation)
QSAId.register(:digital_representation)
