class CsvExportRepresentations < CsvExport

  def columns
    [
      Column.new('Representation ID', proc{|record| record.id}),
      Column.new('Representation Name', proc{|record| record.title}),
      Column.new('Representation Type', proc{|record| record.type}),
      Column.new('Format', proc{|record| record.physical_representation_format}),
      Column.new('Parent Item Start Date', proc{|record| record.start_date}),
      Column.new('Certainty', proc{|record| record.start_date_certainty}),
      Column.new('Parent Item End Date', proc{|record| record.end_date}),
      Column.new('Certainty', proc{|record| record.end_date_certainty}),
      Column.new('Parent Item ID', proc{|record| record.associated_record_id}),
      Column.new('RAP Duration', proc{|record| record.rap_years}),
      Column.new('RAP Expiry Date', proc{|record| record.rap_expiry_date}),
      Column.new('Access Category', proc{|record| record.access_category}),
      Column.new('RAP Publish Details?', proc{|record| record.rap_publish_details}),
      Column.new('RAP Inherited?', proc{|record| record.rap_inherited}),
      Column.new('RAP Inherited from Parent Item?', proc{|record| record.rap_inherited_from_parent_item}),
      Column.new('Contained Within', proc{|record| record.contained_within}),
      Column.new('Top Container', proc{|record| record.top_container}),
      Column.new('Home Location', proc{|record| record.home_location}),
      Column.new('Current Location', proc{|record| record.current_location}),
      Column.new('Availability', proc{|record| record.availability}),
      Column.new('Colour', proc{|record| record.colour}),
      Column.new('File Size', proc{|record| record.file_size}),
      Column.new('File Type', proc{|record| record.file_type}),
      Column.new('Digital File Attached?', proc{|record| record.digital_file_attached}),
      Column.new('File Issue Allowed?', proc{|record| record.file_issue_allowed}),
      Column.new('Exhibition Quality?', proc{|record| record.exhibition_quality}),
      Column.new('Intended Use', proc{|record| record.intended_use}),
      Column.new('Significance', proc{|record| record.significance}),
      Column.new('Inherit Significance?', proc{|record| record.inherit_significance}),
      # Column.new('Sensitivity Label', proc{|record| record.sensitivity_label}), FIXME NOT INDEXED ON REPRESENTATION
      Column.new('Archivist Approved?', proc{|record| record.archivist_approved}),
      Column.new('Approval Date', proc{|record| record.archivist_approval_date}),
      Column.new('Approved By', proc{|record| record.archivist_approved_by}),
      Column.new('Published?', proc{|record| record.published}),
      Column.new('Other Restrictions', proc{|record| record.other_restrictions}),
      Column.new('Agency Control No.', proc{|record| record.agency_control_number}),
      Column.new('Previous System Identifier', proc{|record| record.previous_system_identifier}),
      Column.new('Original Registration Date', proc{|record| record.original_registration_date}),
      Column.new('Accession Status', proc{|record| record.accessioned_retention_status}),
      Column.new('Disposal Class', proc{|record| record.disposal_class}),
      Column.new('Monetary Value', proc{|record| record.monetary_value}),
      Column.new('No. of Movements', proc{|record| record.number_of_movements}),
      Column.new('Conservation Treatment Status', proc{|record| record.treatment_status}),
      Column.new('Citation', proc{|record| record.citation}),
      Column.new('Created Date', proc{|record| record.created_date}),
      Column.new('Created By', proc{|record| record.created_by}),
      Column.new('Last Modified Date', proc{|record| record.last_modified_date}),
      Column.new('Last Modified By', proc{|record| record.last_modified_by}),
    ]
  end

end